// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10_HIrdAGq-HQ9aiQPrP7xnquxH8sjxQ',
    appId: '1:1079459696123:web:c7537f16dd763449a0cf5e',
    messagingSenderId: '1079459696123',
    projectId: 'cachmoney-8f3b8',
    authDomain: 'cachmoney-8f3b8.firebaseapp.com',
    storageBucket: 'cachmoney-8f3b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnROXOVwRD1Mrpoq33_0uovmSP_MB--sA',
    appId: '1:1079459696123:android:a0d65f46e249d932a0cf5e',
    messagingSenderId: '1079459696123',
    projectId: 'cachmoney-8f3b8',
    storageBucket: 'cachmoney-8f3b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2t_FTWZ2_ApYzqRDVUhDVQdRhZhUnAn4',
    appId: '1:1079459696123:ios:dc086fd5551afe61a0cf5e',
    messagingSenderId: '1079459696123',
    projectId: 'cachmoney-8f3b8',
    storageBucket: 'cachmoney-8f3b8.firebasestorage.app',
    iosBundleId: 'com.example.cashMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2t_FTWZ2_ApYzqRDVUhDVQdRhZhUnAn4',
    appId: '1:1079459696123:ios:dc086fd5551afe61a0cf5e',
    messagingSenderId: '1079459696123',
    projectId: 'cachmoney-8f3b8',
    storageBucket: 'cachmoney-8f3b8.firebasestorage.app',
    iosBundleId: 'com.example.cashMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA10_HIrdAGq-HQ9aiQPrP7xnquxH8sjxQ',
    appId: '1:1079459696123:web:d486da951b5ca585a0cf5e',
    messagingSenderId: '1079459696123',
    projectId: 'cachmoney-8f3b8',
    authDomain: 'cachmoney-8f3b8.firebaseapp.com',
    storageBucket: 'cachmoney-8f3b8.firebasestorage.app',
  );
}